Ext.define("core.sys.menu.view.MenuForm",{
	extend:"Ext.form.Panel",
	alias:"widget.menu.menuform",
	layout:{
		type:"vbox",
		align:"left"
	},
//	align:"left",
	frame:true,
	title:"菜单信息",
	defaults:{
			selectOnFocus:true,
			msgTarget:"side", //提示信息现在的位置
			columnWidth:.4
	},
	items:[{
				xtype:"textfield",
				fieldLabel:"主键",
				name:"menuId",
				hidden:true
			},{
				xtype:"textfield",
				fieldLabel:"菜单名称",
				name:"menuName"
				
			},{
				xtype:"textfield",
				fieldLabel:"模块编码",
				name:"moduleCode"
			},{
				xtype:"filefield",
				fieldLabel:"小图标",
				name:"icon"	
			},{
				xtype:"filefield",
				fieldLabel:"桌面图标",
				name:"bigIcon"	
			},{
				xtype:"textfield",
				fieldLabel:"菜单类型",
				name:"nodeInfoType"	
			},{
				xtype:"textfield",
				fieldLabel:"配置信息",
				name:"nodeInfo",
				width:350,
				columnWidth:.6
			},{
				xtype:"numberfield",
				fieldLabel:"排序",
				name:"orderIndex"
			},{
				xtype:"textfield",
				fieldLabel:"父节点",
				name:"parentId",
				hidden:true
			},{
				xtype:"button",
				ref:"submit",
				text:"保存"
			}]
});