Ext.define("core.test.view.TestPanel",{
	extend:"core.app.base.BasePanel",
	alias:"widget.testpanel",
	funCode:"testmodule_main",
	itemId:"testmodule_main_basepanel",
	funData:{
        action:"", //请求Action
        whereSql:"",//表格查询条件
        orderSql:"",//表格排序条件
        modelName:"",//实体全路径
        tableName:"",//表名
        pkName:"name",
        defaultObj:{name:"张文友",birthday:"@createTime@"},//默认信息，用于表格添加的时候字段默认值
        childFun:[]
    },
	items:[{
		xtype:"testgrid"
	},{
		xtype:"testform",
		hidden:true
	}]
});